baseurl = "https://www.example.com/"
languageCode = "en-us"
title = "BlackFlow Theme Demo"
theme = "BlackFlow"

enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; 2019. All rights reserved."

preserveTaxonomyNames = true
summaryLength = 40
hasCJKLanguage = true

[params]
    brand = "BlackFlow"
    subtitle = "A brief black style Hugo theme."
    dateformat = "2006-01-02 15:04"
    math = true
    max_taxonomy_terms = 3
    highlightjs = "androidstudio"
    highlightjs_extra_languages = ["yaml","kotlin"]
    comment_system = "gitalk"
    comment_system_client_id = "2e0f8f3c6e43d7554f1e"
    comment_system_client_secret = "17ca828f17eafa59907768c5988a01f05d915aec"
    comment_system_owner = "Hugo-BlackFlow"
    comment_system_repo = "hugo-blackflow.github.io"

[social]
    github = "Hugo-BlackFlow"
    email = "hugo-blackflow@outlook.com"

[menu]
    # Shown in the side menu.
    [[menu.main]]
        name = "Home"
        pre = "<i class='fa fa-home fa-fw'></i>"
        weight = 1
        identifier = "home"
        url = "/"
    [[menu.main]]
        name = "Posts"
        pre = "<i class='fa fa-list fa-fw'></i>"
        weight = 2
        identifier = "posts"
        url = "/posts/"
    [[menu.main]]
        name = "Topics"
        pre = "<i class='fa fa-book fa-fw'></i>"
        weight = 3
        identifier = "topics"
        url = "/topics/"
    [[menu.main]]
        name = "Tags"
        pre = "<i class='fa fa-tags fa-fw'></i>"
        weight = 4
        identifier = "tags"
        url = "/tags/"

[ taxonomies ]
    tag = "tags"
    topic = "topics"